workspace(name = "up_and_running")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Go rules

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "207fad3e6689135c5d8713e5a17ba9d1290238f47b9ba545b63d9303406209c6",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.24.7/rules_go-v0.24.7.tar.gz",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.24.7/rules_go-v0.24.7.tar.gz",
    ],
)

# Gazelle is a tool for auto-creating BUILD.bazel files for Go
# projects ("bazel run //:gazelle"). It provides a "happy path"
# for Go projects - the BUILD files you see here were generated
# by Gazelle, not by hand.

http_archive(
    name = "bazel_gazelle",
    sha256 = "b85f48fa105c4403326e9525ad2b2cc437babaa6e15a3fc0b1dbab0ab064bc7c",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.22.2/bazel-gazelle-v0.22.2.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.22.2/bazel-gazelle-v0.22.2.tar.gz",
    ],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains(
    go_version = "1.15.5",  # Defaults to latest
)

# tip:
# bazel build @io_bazel_rules_go//:go_info
# cat bazel-bin/external/io_bazel_rules_go/darwin_amd64_stripped/go_info%/go_info_report
# Compare to the output of "go version"

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")

gazelle_dependencies()

# Dependencies

# tip:
# bazel run //:gazelle -- update-repos github.com/mattn/go-slim

go_repository(
    name = "com_github_mattn_go_slim",
    importpath = "github.com/mattn/go-slim",
    sum = "h1:M3l0/LNEemy7ykM6qCZylkWmFPyvDLDCl7bZPLTfaBQ=",
    version = "v0.0.0-20200618151855-bde33eecb5ee",
)

# From the rules_go documentation:

# "Note that go build won't be aware of dependencies listed in WORKSPACE,
# so you may want to download your dependencies into your GOPATH or module
# cache so that your tools are aware of them. You may also need to check
# in generated files."

# Thus: go get github.com/mattn/go-slim
