version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  bazel_linux:
    docker:
      - image: l.gcr.io/google/bazel:latest
    resource_class: large
    steps:
      - checkout

      - run:
          command: |
            cd 1-up-and-running
            # 3.7.0 not yet published, https://console.cloud.google.com/gcr/images/cloud-marketplace-containers/GLOBAL/google/bazel?gcrImageListsize=30
            echo 3.5.0 >.bazelversion
            bazel version
            ./exercise.sh

      - run:
          command: |
            cd 2-java-tooling
            echo 3.5.0 >.bazelversion
            ./exercise.sh

      - run:
          command: |
            cd 3-java-dependencies
            echo 3.5.0 >.bazelversion
            ./exercise.sh

      - run:
          command: |
            cd 4-multi-language
            echo 3.5.0 >.bazelversion
            ./exercise.sh

      - run:
          command: |
            cd 5-full-stack
            echo 3.5.0 >.bazelversion
            ./exercise.sh

      - run:
          command: |
            cd 6-sprawling-suite
            echo 3.5.0 >.bazelversion
            ./exercise.sh

      - run:
          command: |
            cd 7-large-angular
            echo 3.5.0 >.bazelversion
            ./exercise.sh

  bazel_windows:
    executor:
      name: win/default
      shell: bash.exe
      size: large
    steps:
      - checkout
      - run:
          command: |
            curl -sSL https://github.com/bazelbuild/bazel/releases/download/3.7.0/bazel-3.7.0-windows-x86_64.exe >/c/Go/bin/bazel
      - run:
          command: |
            cd 1-up-and-running
            ./exercise.sh

      - run:
          command: |
            cd 2-java-tooling
            ./exercise.sh

      - run:
          command: |
            cd 3-java-dependencies
            ./exercise.sh

      - run:
          command: |
            cd 4-multi-language
            ./exercise.sh

      - run:
          command: |
            cd 5-full-stack
            ./exercise.sh

      - run:
          command: |
            cd 6-sprawling-suite
            ./exercise.sh

      - run:
          command: |
            cd 7-large-angular
            ./exercise.sh

workflows:
  version: 2
  both_platforms:
    jobs:
      - bazel_linux
      - bazel_windows
