version: 2.1

orbs:
  win: circleci/windows@2.4.1

jobs:
  bazel_linux:
    docker:
      - image: ubuntu:rolling
      # There used to be an up to date image published by Google, see
      # https://console.cloud.google.com/gcr/images/cloud-marketplace-containers/GLOBAL/google/bazel?gcrImageListsize=30
      # https://github.com/bazelbuild/continuous-integration/issues/1060

    resource_class: large
    steps:
      - checkout

      - run:
          command: |
            apt-get update
            export DEBIAN_FRONTEND=noninteractive
            apt-get install -q -y curl g++ zlib1g-dev openjdk-11-jdk patch python3 python3-pip python3-distutils python-is-python3 cc65
            curl -sSL https://github.com/bazelbuild/bazelisk/releases/download/v1.10.1/bazelisk-linux-amd64 >/usr/local/bin/bazel
            chmod +x /usr/local/bin/bazel
            python3 -m pip install pip-tools

      - run:
          command: |
            cd 01-up-and-running
            ./exercise.sh

      - run:
          command: |
            cd 03-java-dependencies
            ./exercise.sh

      - run:
          command: |
            cd 04-multi-language
            ./exercise.sh

      - run:
          command: |
            cd 05-cpp
            ./exercise.sh

      - run:
          command: |
            cd 06-python
            ./exercise.sh

      - run:
          command: |
            cd 07-full-stack
            ./exercise.sh

      - run:
          command: |
            cd 08-sprawling-suite
            ./exercise.sh

      - run:
          command: |
            cd 09-large-angular
            ./exercise.sh

      - run:
          command: |
            cd 11-cross
            ./exercise.sh

  bazel_windows:
    executor:
      name: win/default
      # TODO Bazel under Bash on windows has problems - see this doc, and fix it.
      # https://docs.bazel.build/versions/main/windows.html#running-bazel-msys2-shell-vs-command-prompt-vs-powershell
      shell: powershell.exe
      size: large
    steps:
      - checkout
      - run: systeminfo

      - run:
          shell: cmd.exe
          command: |
            curl -sSL https://releases.bazel.build/5.0.0/rc2/bazel-5.0.0rc2-windows-x86_64.exe >/ProgramData/nvm/bazel.exe
            # python and pip-tools already present in Circle CI's Windows environment.

      - run:
          command: |
            cd 01-up-and-running
            bazel version
            bazel fetch ...
            bazel build ...
            bazel build //groceries:groceries
            bazel build //groceries

      - run:
          command: |
            cd 03-java-dependencies
            bazel build ...
            bazel test ... --test_verbose_timeout_warnings --test_output=errors
            bazel run :hello-world
            bazel run //app-one/src/main/java/com/example/myproject:hello-world
            bazel run //app-one/src/main/java/com/example/myproject:hello-data

      - run:
          command: |
            cd 04-multi-language
            bazel build ...
            bazel build :service-deploy

      - run:
          command: |
            cd 05-cpp
            echo TODO attempt C++ 17 setup on Windows bash exercise.sh

      - run:
          command: |
            cd 06-python
            bazel build "..."
            # TODO find and fix problem with Python-Gazelle and Windows: bazel run //app:app_bin

      - run:
          command: |
            cd 07-full-stack
            bazel build ...

      - run:
          command: |
            cd 08-sprawling-suite
            bazel fetch ...
            bazel build ... --jobs=2

      - run:
          command: |
            cd 09-large-angular
            echo SKIPPING rules_nodejs windows compat problem, bash exercise.sh

workflows:
  version: 2
  both_platforms:
    jobs:
      - bazel_linux
      - bazel_windows
