version: 2.1

orbs:
  win: circleci/windows@2.4.1

jobs:
  bazel_linux:
    docker:
      - image: ubuntu:rolling
      # There used to be an up to date image published by Google, see
      # https://console.cloud.google.com/gcr/images/cloud-marketplace-containers/GLOBAL/google/bazel?gcrImageListsize=30
      # https://github.com/bazelbuild/continuous-integration/issues/1060

    resource_class: large
    steps:
      - checkout

      - run:
          command: |
            apt-get update
            apt-get install -y curl g++ zlib1g-dev openjdk-11-jdk patch
            curl -sSL https://github.com/bazelbuild/bazelisk/releases/download/v1.10.1/bazelisk-linux-amd64 >/usr/local/bin/bazel
            chmod +x /usr/local/bin/bazel

      - run:
          command: |
            cd 1-up-and-running
            ./exercise.sh

      - run:
          command: |
            cd 2-java-tooling
            ./exercise.sh

      - run:
          command: |
            cd 3-java-dependencies
            ./exercise.sh

      - run:
          command: |
            cd 4-multi-language
            ./exercise.sh

      - run:
          command: |
            cd 5-full-stack
            ./exercise.sh

      - run:
          command: |
            cd 6-sprawling-suite
            ./exercise.sh

      - run:
          command: |
            cd 7-large-angular
            ./exercise.sh

  bazel_windows:
    executor:
      name: win/default
      shell: bash.exe
      size: large
    steps:
      - checkout
      - run:
          command: |
            mkdir -p /c/Go/bin  # On the PATH but not in use yet
            curl -sSL https://releases.bazel.build/5.0.0/rc2/bazel-5.0.0rc2-windows-x86_64.exe >/c/Go/bin/bazel

      - run:
          command: |
            cd 1-up-and-running
            ./exercise.sh

      - run:
          command: |
            cd 2-java-tooling
            ./exercise.sh

      - run:
          command: |
            cd 3-java-dependencies
            ./exercise.sh

      - run:
          command: |
            cd 4-multi-language
            ./exercise.sh

      - run:
          command: |
            cd 5-full-stack
            echo SKIPPING rules_nodejs windows compat problem ./exercise.sh

      - run:
          command: |
            cd 6-sprawling-suite
            ./exercise.sh

      - run:
          command: |
            cd 7-large-angular
            echo SKIPPING rules_nodejs windows compat problem ./exercise.sh

workflows:
  version: 2
  both_platforms:
    jobs:
      - bazel_linux
      - bazel_windows
