workspace(
    name = "python_example",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Python support

# "Currently the core rules are bundled with Bazel itself, and the
# symbols in this repository are simple aliases"

http_archive(
    name = "rules_python",
    sha256 = "cd6730ed53a002c56ce4e2f396ba3b3be262fd7cb68339f0377a45e8227fe332",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.5.0/rules_python-0.5.0.tar.gz",
)

load("@rules_python//python:pip.bzl", "pip_install")

# Run pip, create Bazel targets for the packages thereing.

# By default, pip_install uses the system command "python3" - this is
# a rough edge, because it might not match the Python you use in
# builds.

pip_install(
    name = "app_deps",
    requirements = "//app:requirements.txt",
)
