workspace(name = "java_tooling")

load(
    "@bazel_tools//tools/build_defs/repo:http.bzl",
    "http_archive",
    "http_jar",
)

# "New" Java support

http_archive(
    name = "rules_java",
    sha256 = "220b87d8cfabd22d1c6d8e3cdb4249abd4c93dcc152e0667db061fb1b957ee68",
    url = "https://github.com/bazelbuild/rules_java/releases/download/0.1.1/rules_java-0.1.1.tar.gz",
)

# Merely loading the rule won't transitively execute code inside them to load
# their dependencies. Instead, as the consumer we have to request the rest of the
# setup.

load("@rules_java//java:repositories.bzl", "rules_java_dependencies", "rules_java_toolchains")

rules_java_dependencies()

rules_java_toolchains()

# Bazel-managed JDK:

# Download JDKs; as I understand all will be downloaded, then only the one
# suitable for the platform will be used.

# We are using Azul's builds of OpenJDK:
# https://www.azul.com/downloads/zulu-community/?architecture=x86-64-bit&package=jdk

http_archive(
    name = "jdk11_linux",
    build_file = "@local_jdk//:BUILD.bazel",
    sha256 = "6c79bfe8bb06c82b72ef2f293a14becef56b3078d298dc75fda4225cbb2d3d0c",
    strip_prefix = "zulu11.43.55-ca-jdk11.0.9.1-linux_x64",
    urls = [
        "https://cdn.azul.com/zulu/bin/zulu11.43.55-ca-jdk11.0.9.1-linux_x64.tar.gz",
    ],
)

http_archive(
    name = "jdk11_macos",
    build_file = "@local_jdk//:BUILD.bazel",
    sha256 = "11701b54e62d5cde81a4fa0211776448e38a368c1cfc4ad73bb3bbd628107563",
    strip_prefix = "zulu11.43.55-ca-jdk11.0.9.1-macosx_x64",
    urls = [
        "https://cdn.azul.com/zulu/bin/zulu11.43.55-ca-jdk11.0.9.1-macosx_x64.tar.gz",
    ],
)

http_archive(
    name = "jdk11_windows",
    build_file = "@local_jdk//:BUILD.bazel",
    sha256 = "b619df7a6f625095ee4adb3add44839b0b1af2adc09a16c7312ca96bb2b61ec9",
    strip_prefix = "zulu11.43.55-ca-jdk11.0.9.1-win_x64",
    urls = [
        "https://cdn.azul.com/zulu/bin/zulu11.43.55-ca-jdk11.0.9.1-win_x64.zip",
    ],
)

# Retrieve a dependency JAR in the simplest available way. We'll see
# more complex mechanisms later.

http_jar(
    name = "guava",
    sha256 = "56b292df9ec29d102820c1fd7dd581cd749d5c416c7b3aeac008dbda3b984cc2",
    url = "https://repo1.maven.org/maven2/com/google/guava/guava/30.0-jre/guava-30.0-jre.jar",
)
