workspace(name = "java_tooling")

load(
    "@bazel_tools//tools/build_defs/repo:http.bzl",
    "http_archive",
    "http_jar",
)

# "New" Java support

http_archive(
    name = "rules_java",
    sha256 = "34b41ec683e67253043ab1a3d1e8b7c61e4e8edefbcad485381328c934d072fe",
    url = "https://github.com/bazelbuild/rules_java/releases/download/4.0.0/rules_java-4.0.0.tar.gz",
)

# Merely loading the rule won't transitively execute code inside them to load
# their dependencies. Instead, as the consumer we have to request the rest of the
# setup.

load("@rules_java//java:repositories.bzl", "rules_java_dependencies", "rules_java_toolchains")

rules_java_dependencies()

rules_java_toolchains()

# Bazel-managed JDK:jdk11_linux

# As of late 2021, Bazel passes a flag to Java which generates
# warnings starting at v15, and errors at v17.
# https://github.com/bazelbuild/bazel/issues/13784

# We are using Azul's builds of OpenJDK:
# https://www.azul.com/downloads/zulu-community/?architecture=x86-64-bit&package=jdk

# Also, Bazel 5/6 greatly enhances this, adding first-class support for different JDKs.
# See the param --java_runtime_version

http_archive(
    name = "jdk15_linux",
    build_file = "@local_jdk//:BUILD.bazel",
    sha256 = "fff7500fc8ef63e298039087a9b7eb816af2f8bc90e3d7a8eaa950152660eff8",
    strip_prefix = "zulu15.36.13-ca-jdk15.0.5-linux_x64",
    urls = [
        "https://cdn.azul.com/zulu/bin/zulu15.36.13-ca-jdk15.0.5-linux_x64.tar.gz",
    ],
)

http_archive(
    name = "jdk15_macos",
    build_file = "@local_jdk//:BUILD.bazel",
    sha256 = "e89e4b1ad499b59bfc74edef0975654a4033cdb9887a646c98cb35f41de72c06",
    strip_prefix = "zulu15.36.13-ca-jdk15.0.5-macosx_x64",
    urls = [
        "https://cdn.azul.com/zulu/bin/zulu15.36.13-ca-jdk15.0.5-macosx_x64.tar.gz",
    ],
)

http_archive(
    name = "jdk15_windows",
    build_file = "@local_jdk//:BUILD.bazel",
    sha256 = "9c607ccd3817dd63d514adf8e66ceedba951a1b7154c62ba3f18e02fe7b8993b",
    strip_prefix = "zulu15.36.13-ca-jdk15.0.5-win_x64",
    urls = [
        "https://cdn.azul.com/zulu/bin/zulu15.36.13-ca-jdk15.0.5-win_x64.zip",
    ],
)

# Retrieve a dependency JAR in the simplest available way. We'll see
# more complex mechanisms later.

http_jar(
    name = "guava",
    sha256 = "d5be94d65e87bd219fb3193ad1517baa55a3b88fc91d21cf735826ab5af087b9",
    url = "https://repo1.maven.org/maven2/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar",
)
